ALTER TABLE facts ADD COLUMN IF NOT EXISTS confidence      FLOAT       NOT NULL DEFAULT 1.0;
ALTER TABLE facts ADD COLUMN IF NOT EXISTS source_weight   FLOAT       NOT NULL DEFAULT 1.0;
ALTER TABLE facts ADD COLUMN IF NOT EXISTS confirmed_count INT         NOT NULL DEFAULT 0;
ALTER TABLE facts ADD COLUMN IF NOT EXISTS last_seen_at    TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE facts ADD COLUMN IF NOT EXISTS updated_at      TIMESTAMPTZ NOT NULL DEFAULT now();
