-- dprompt-125: Rel-type aliases for LLM variation normalization
-- Maps non-canonical rel_type variations to canonical Wikidata ontology
-- Seeded with common LLM patterns; re_embedder extends over time

CREATE TABLE IF NOT EXISTS rel_type_aliases (
    id SERIAL PRIMARY KEY,
    canonical_rel_type VARCHAR(255) NOT NULL,
    alias VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT NOW(),
    source VARCHAR(50) DEFAULT 'ontology',  -- 'ontology' (seeds), 'llm_learned' (re_embedder), 'user'
    confidence FLOAT DEFAULT 1.0,
    FOREIGN KEY (canonical_rel_type) REFERENCES rel_types(rel_type) ON DELETE CASCADE
);

CREATE INDEX idx_rel_type_aliases_alias ON rel_type_aliases(alias);
CREATE INDEX idx_rel_type_aliases_canonical ON rel_type_aliases(canonical_rel_type);

-- Seed with Wikidata/common LLM variations (dprompt-125)
-- Identity relations
INSERT INTO rel_type_aliases (canonical_rel_type, alias, source) VALUES
('pref_name', 'preferred_name', 'ontology'),
('pref_name', 'calls_self', 'ontology'),
('also_known_as', 'prefers_name', 'ontology'),
('also_known_as', 'preferred_name', 'ontology'),
('also_known_as', 'goes_by', 'ontology'),
('also_known_as', 'known_as', 'ontology'),
('also_known_as', 'nickname', 'ontology'),
('also_known_as', 'called', 'ontology'),
('same_as', 'is_same_as', 'ontology'),
('instance_of', 'is_a', 'ontology'),
('instance_of', 'is_an', 'ontology'),
('instance_of', 'type_of', 'ontology'),
('instance_of', 'a_type_of', 'ontology'),
('subclass_of', 'subtype_of', 'ontology'),
('member_of', 'belongs_to', 'ontology'),
('member_of', 'member', 'ontology'),
('part_of', 'is_part_of', 'ontology'),
('part_of', 'component_of', 'ontology'),
('parent_of', 'has_child', 'ontology'),
('parent_of', 'has_children', 'ontology'),
('parent_of', 'has_son', 'ontology'),
('parent_of', 'has_daughter', 'ontology'),
('parent_of', 'has_kid', 'ontology'),
('parent_of', 'parent', 'ontology'),
('parent_of', 'is_parent_of', 'ontology'),
('child_of', 'son_of', 'ontology'),
('child_of', 'daughter_of', 'ontology'),
('child_of', 'kid_of', 'ontology'),
('child_of', 'is_child_of', 'ontology'),
('child_of', 'child', 'ontology'),
('spouse', 'spouse_of', 'ontology'),
('spouse', 'married_to', 'ontology'),
('spouse', 'husband_of', 'ontology'),
('spouse', 'wife_of', 'ontology'),
('sibling_of', 'sibling', 'ontology'),
('sibling_of', 'brother_of', 'ontology'),
('sibling_of', 'sister_of', 'ontology'),
('owns', 'owned_by', 'ontology'),
('owns', 'has', 'ontology'),
('has_pet', 'owns_pet', 'ontology'),
('has_pet', 'pet', 'ontology'),
('works_for', 'employed_by', 'ontology'),
('works_for', 'employment', 'ontology'),
('works_for', 'work', 'ontology'),
('works_for', 'employee_of', 'ontology'),
('located_in', 'located', 'ontology'),
('located_in', 'located_at', 'ontology'),
('located_in', 'location', 'ontology'),
('lives_in', 'lives', 'ontology'),
('lives_in', 'residence', 'ontology'),
('lives_in', 'resides', 'ontology'),
('lives_in', 'resides_in', 'ontology'),
('lives_at', 'lives', 'ontology'),
('born_in', 'born', 'ontology'),
('born_in', 'birthplace', 'ontology'),
('born_in', 'place_of_birth', 'ontology'),
('born_on', 'birthday', 'ontology'),
('born_on', 'date_of_birth', 'ontology'),
('born_on', 'dob', 'ontology'),
('age', 'years_old', 'ontology'),
('age', 'aged', 'ontology'),
('occupation', 'job', 'ontology'),
('occupation', 'profession', 'ontology'),
('occupation', 'career', 'ontology'),
('occupation', 'works_as', 'ontology'),
('educated_at', 'school', 'ontology'),
('educated_at', 'education', 'ontology'),
('educated_at', 'studied_at', 'ontology'),
('educated_at', 'attends', 'ontology'),
('knows', 'knows_of', 'ontology'),
('friend_of', 'friend', 'ontology'),
('friend_of', 'is_friend_of', 'ontology'),
('met', 'meet', 'ontology'),
('likes', 'liked', 'ontology'),
('dislikes', 'disliked', 'ontology')
ON CONFLICT (alias) DO NOTHING;
