-- Migration 274: episodic_log.turn_key — SERVER-SIDE idempotency for the retained-turn floor.
-- Date: 2026-09-14. Campaign: the internal design record (round 3, gap C).
--
-- WHY
-- ---
-- The MCP retries POST /episodic/append once on a client-side transport failure. A ReadTimeout is
-- "sent, unknown": the first INSERT may still be committing when the second attempt arrives.
-- Measured live (round 2, append budget 0.02s): the round-2 SELECT-then-INSERT dedup window
-- RACED the in-flight write — 3 of 6 seats got the verbatim turn TWICE, and a read-back probe
-- fired before the commit answered "absent" for a row that landed 4-165 ms later.
--
-- The fix is a per-turn idempotency KEY, generated by the client ONCE per turn and carried by
-- every attempt for that turn, enforced by a PARTIAL UNIQUE INDEX in the database:
--   INSERT ... ON CONFLICT (turn_key) WHERE turn_key IS NOT NULL DO NOTHING RETURNING id
-- PostgreSQL blocks the second in-flight INSERT on the index until the first commits or aborts,
-- then reports the conflict — so two attempts can NEVER produce two rows, and the SECOND
-- attempt's answer (the existing id, `deduplicated: true`) IS the read-back. A genuine
-- re-statement of the same words later is a NEW turn with a NEW key and still appends — which is
-- why the key is a per-turn token and NOT a hash of the content.
--
-- Nullable + partial: a keyless writer (the re_embedder's document lane, any older client) keeps
-- today's append semantics untouched. Idempotent DDL (IF NOT EXISTS); the boot-migration ledger
-- (src/provisioning/boot_migrations.py) stamps this file per schema so it runs once per tenant.
-- ⚠️ The SAME column + index live in src/provisioning/templates/user_schema.sql — a migration-only
-- change silently skips every NEWLY PROVISIONED tenant (the 197 failure shape).

DO $$
DECLARE
    _schema TEXT;
BEGIN
    FOR _schema IN
        SELECT schema_name
        FROM information_schema.schemata
        WHERE schema_name LIKE 'faultline\_%'
        ORDER BY schema_name
    LOOP
        -- Skip a schema with no episodic_log table (partial / aborted provisioning).
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = _schema
              AND table_name   = 'episodic_log'
        ) THEN
            RAISE NOTICE 'migration 274: skipping % (no episodic_log)', _schema;
            CONTINUE;
        END IF;

        EXECUTE format(
            'ALTER TABLE %I.episodic_log ADD COLUMN IF NOT EXISTS turn_key TEXT', _schema);

        EXECUTE format(
            'CREATE UNIQUE INDEX IF NOT EXISTS idx_episodic_log_turn_key'
            '    ON %I.episodic_log (turn_key) WHERE turn_key IS NOT NULL', _schema);

        EXECUTE format(
            'COMMENT ON COLUMN %I.episodic_log.turn_key IS '
            '''Per-turn idempotency key (client-generated, one per turn, shared by every '
            'retry attempt of that turn). Partial UNIQUE: two in-flight attempts can never '
            'produce two rows; NULL for keyless writers (migration 274).''', _schema);

        RAISE NOTICE 'migration 274: episodic_log.turn_key ensured in %', _schema;
    END LOOP;
END $$;
